apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-api-gateway-server-pod
  labels:
    app: spring-api-gateway-server
  namespace: tarsidi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-api-gateway-server
  template:
    metadata:
      labels:
        app: spring-api-gateway-server
    spec:
      containers:
      - name: spring-api-gateway-server
        image: sidie88/spring-api-gateway-server:v1
        env:
        - name: MY_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: RABBIT_URI
          value: amqp://rabbitmq-service.$(MY_NAMESPACE).svc.cluster.local:5672
        - name: _JAVA_OPTIONS
          value: |-
                  -Dspring.zipkin.base-url=http://zipkin-service.$(MY_NAMESPACE).svc.cluster.local:9411/ 
                  -Dzuul.routes.currencyexchange.path=/currency-exchange-service/** 
                  -Dzuul.routes.currencyexchange.url=http://currency-exchange-service.$(MY_NAMESPACE).svc.cluster.local 
                  -Dzuul.routes.currencyconverter.path=/currency-conversion-service/** 
                  -Dzuul.routes.currencyconverter.url=http://currency-conversion-service.$(MY_NAMESPACE).svc.cluster.local
        ports:
        - containerPort: 8762
---
apiVersion: v1
kind: Service
metadata:
  name: spring-api-gateway-services
  namespace: tarsidi
spec:
  type: NodePort
  ports:
  - port: 8762
    targetPort: 8762
    #nodePort: 30000
  selector:
    app: spring-api-gateway-server
