apiVersion: apps/v1
kind: Deployment
metadata:
  name: currency-exchange-pod
  labels:
    app: currency-exchange
  namespace: tarsidi
spec:
  replicas: 3
  selector:
    matchLabels:
      app: currency-exchange
  template:
    metadata:
      labels:
        app: currency-exchange
    spec:
      containers:
      - name: currency-exchange
        image: sidie88/currency-exchange-sevice:log-amqp
        env:
        - name: MY_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: RABBIT_URI
          value: amqp://rabbitmq-service.$(MY_NAMESPACE).svc.cluster.local:5672
        - name: _JAVA_OPTIONS
          value: |- 
                  -Dspring.zipkin.base-url=http://zipkin-service.$(MY_NAMESPACE).svc.cluster.local:9411/
                  -Dspring.zipkin.sender.type=rabbit
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: currency-exchange-service
  namespace: tarsidi
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: currency-exchange